remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: Coffee Rings – Info Pages
description: "Privacy & Support for the Coffee Rings app"
logo: /assets/coffeerings.png
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
  repository_url: ""
  owner_url: ""
